#pragma once

#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_PROCESS_KEY_REPRESS

/* KEYBOARD CONFIGS */
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DPI_OPTIONS { 900, 1050, 1200, 1600 }
#define PLOOPY_DPI_DEFAULT 1

/* USER CONFIGS */
#define PLOOPY_DIVISOR_OPTIONS { 160, 120, 80, 60, 40 }
#define PLOOPY_DIVISOR_DEFAULT 2

#define BURST_DELAY_DEFAULT 60
#define BURST_DELAY_MIN 30
#define BURST_DELAY_MAX 200
#define BURST_DELAY_CHANGE_SMALL 10
#define BURST_DELAY_CHANGE_LARGE 50

#define BURST_COUNT_DEFAULT 5
#define BURST_COUNT_MIN 5
#define BURST_COUNT_MAX 20
#define BURST_COUNT_CHANGE_SMALL 1
#define BURST_COUNT_CHANGE_LARGE 5
